services:
  - type: web
    name: rennsz-streamer-website
    env: node
    runtime: node
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUBLIC_URL
        value: https://rennsz-streamer-website.onrender.com
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true
    plan: free